### ISSUE TITLE
No DateTime Support and IList 

### ISSUE THREAD

**Issue by sriman94** [couchbaselabs/Couchbase.Lite.Mapping#4]
As per Borrden's (from CouchBase) I used the mapping library to convert objects to mutable docs and vice versa. But if my entity contains datetime field in it, mapping throwing error as it supports only DateTimeOffSet. Any alternative for this ?

Also is there any support for converting IList to mutable docs ?

**Comment by rhedgpeth** [comment]
Hey @sriman94!

I'll need to add conditions to handle converting to/from DateTimeOffset since this is a requirement of Couchbase Lite. Unfortunately, there's no great way to work around this other than swapping out for DateTimeOffset. Also, once I add in the ability to include DateTime it's going to default to the timezone the user is currently in which could potentially cause issues if you're storing something like a UTC time, for example. That's ultimately why the DateTimeOffset is being used in the first place.

For converting a collection of objects to a collection of mutable documents you can use [lambda expressions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions).

`var users = new List<User> { user1, user2 }; `
`var mutableDocs = users.Select(u => u.ToMutableDocument());`

I'll add support for collection conversion as a feature request, and try to have it out in the next version of the Nuget along with DateTime support.

**Comment by rhedgpeth** [comment]
@sriman94 I have added support for DateTime conversions in v1.0.5, which I just released.

https://www.nuget.org/packages/Couchbase.Lite.Mapping/1.0.5
